language: python

sudo: false

python:
    - "3.4"

services:
    - mongodb
    - elasticsearch
    - redis-server

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -r requirements.txt --use-mirrors && pip install coveralls==1.0a2

script:
    - nosetests --with-coverage --cover-package=content_api
    - behave --format progress2 --logging-level ERROR content_api/features
    - flake8

after_script:
    - killall -9 python
